kind: AIchorManifest
apiVersion: 0.2.2 
   
builder:   
  image: image
  dockerfile: ./build/Dockerfile 
  context: .  
engineName: kao-mutlieng-0602f07f26374f1a
 
spec: 
  operator: jobset  
  image: image 
  command: "python3 -u main.py --operator=jobset --sleep=30 --tb-write=True"   

  tensorboard:
    enabled: true

  types: # 
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

